/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Timer;

/**
 *
 * @author Martin
 */
public class rpgjuego extends javax.swing.JFrame {
    private Object vida1;

    /**
     * Creates new form rpgjuego
     */
    public rpgjuego() {
        initComponents();
        
        //turno(turn);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pb_vida2 = new javax.swing.JProgressBar();
        pb_vida1 = new javax.swing.JProgressBar();
        jugando = new javax.swing.JLabel();
        pj1 = new javax.swing.JLabel();
        pj2 = new javax.swing.JLabel();
        np1 = new javax.swing.JLabel();
        np2 = new javax.swing.JLabel();
        atacar1 = new javax.swing.JButton();
        curar1 = new javax.swing.JButton();
        combinado1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        setPreferredSize(new java.awt.Dimension(2000, 1366));

        pb_vida2.setValue(100);

        pb_vida1.setValue(100);

        jugando.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jugando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugando.setText("JUGANDO");

        pj1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/PieceValkiriabltG.png"))); // NOI18N
        pj1.setText("jLabel1");

        pj2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/meliodas.png"))); // NOI18N
        pj2.setText("jLabel2");

        np1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/PieceKnightbltG.png"))); // NOI18N

        np2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/eren.png"))); // NOI18N

        atacar1.setText("ATACAR");
        atacar1.setAutoscrolls(true);
        atacar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                atacar1MousePressed(evt);
            }
        });
        atacar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atacar1ActionPerformed(evt);
            }
        });

        curar1.setText("CURAR");
        curar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curar1MousePressed(evt);
            }
        });

        combinado1.setText("Ataque combinado");
        combinado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                combinado1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(pj2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233)
                        .addComponent(pj1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 511, Short.MAX_VALUE)
                        .addComponent(np1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jugando, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(392, 392, 392)))
                .addComponent(np2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(curar1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281)
                        .addComponent(atacar1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(combinado1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(pj2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(pj1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atacar1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(curar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(combinado1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(np2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jugando, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(np1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atacar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atacar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atacar1ActionPerformed

    private void atacar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atacar1MousePressed
        int random = 17;
        int nueva_vida = pb_vida2.getValue()- random;
        pb_vida2.setValue(nueva_vida);
        if(nueva_vida<=0)
        {
            jugando.setText("Haz Ganado");
        }
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                double ataque_random = Math.random()*100;
                
                if(ataque_random<40)
                {
                    System.out.println("Ataque normal");
                    double random = Math.random()*30;
                    int nueva_vida = pb_vida1.getValue()-(int)random;
                    pb_vida1.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        jugando.setText("Ha ganado el caballero");
                    }
                }else if(ataque_random<80)
                {
                    System.out.println("Curarse");
                    double random = Math.random()*25;
                    int nueva_vida = pb_vida2.getValue()+(int)random;
                    pb_vida2.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        jugando.setText("Ha ganado el segundo equipo");
                    }
                }else if(ataque_random<90)
                {
                    System.out.println("Ataque combinado");
                    int nueva_vida = pb_vida2.getValue()+(int)random;
                    pb_vida1.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        jugando.setText("Ha ganado el segundo equipo");
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
        
       // turno(turn);
        //System.out.println("hola mundo");
    }//GEN-LAST:event_atacar1MousePressed

    private void curar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curar1MousePressed
double random = Math.random()*25;
        int nueva_vida = pb_vida1.getValue()+(int) random;
        pb_vida1.setValue(nueva_vida);
        if(nueva_vida<=0)
        {
            jugando.setText("Haz Ganado");
        }       
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                double ataque_random = Math.random()*100;
                
                if(ataque_random<40)
                {
                    System.out.println("Ataque normal");
                    double random = Math.random()*30;
                    int nueva_vida = pb_vida1.getValue()-(int)random;
                    pb_vida1.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        jugando.setText("Ha ganado el segundo equipo");
                    }
                }else if(ataque_random<80)
                {
                    System.out.println("Curarse");
                    double random = Math.random()*25;
                    int nueva_vida = pb_vida2.getValue()+(int)random;
                    pb_vida2.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        jugando.setText("Ha ganado el segundo equipo");
                    }
                }else if(ataque_random<90)
                {
                    System.out.println("Ataque combinado");
                    double random = Math.random()*90;
                    int nueva_vida = pb_vida2.getValue()-(int)random;
                    pb_vida1.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        jugando.setText("Ha ganado el segundo equipo");
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
        //turno(turn);
    }//GEN-LAST:event_curar1MousePressed

    private void combinado1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combinado1MousePressed
        double random = Math.random()*90;
        int nueva_vida = pb_vida2.getValue()-(int)random;
        pb_vida2.setValue(nueva_vida);
        if(nueva_vida<=0)
        {
            jugando.setText("Haz ganado");
        }
         Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                double ataque_random = Math.random()*100;
                
                if(ataque_random<40)
                {
                    System.out.println("Ataque normal");
                    double random = Math.random()*30;
                    int nueva_vida = pb_vida1.getValue()-(int)random;
                    pb_vida1.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        jugando.setText("Ha ganado el caballero");
                    }
                }else if(ataque_random<80)
                {
                    System.out.println("Curarse");
                    double random = Math.random()*25;
                    int nueva_vida = pb_vida2.getValue()+(int)random;
                    pb_vida2.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        jugando.setText("Ha ganado el segundo equipo");
                    }
                }else if(ataque_random<90)
                {
                    System.out.println("Ataque combinado");
                    double random = Math.random()*90;
                    int nueva_vida = pb_vida2.getValue()-(int)random;
                    pb_vida1.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        jugando.setText("Ha ganado el segundo equipo");
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
        
        //turno(turn);
    }//GEN-LAST:event_combinado1MousePressed

   /* public void turno(int turn){
        System.out.println("hola mundo2");
        System.out.println(turn);
        
       if(turn == 0){
            atacar1.setEnabled(true);
            curar1.setEnabled(true);
            combinado1.setEnabled(true);
            
            atacar2.setEnabled(false);
            curar2.setEnabled(false);
            combinado2.setEnabled(false);
            System.out.println("adios mundo");
            turn = 1;
            System.out.println(turn);
        }else{
            atacar2.setEnabled(true);
            curar2.setEnabled(true);
            combinado2.setEnabled(true);
            
            atacar1.setEnabled(false);
            curar1.setEnabled(false);
            combinado1.setEnabled(false);
            System.out.println("agugu");
            turn = 0;
        }
        
    }
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rpgjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rpgjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rpgjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rpgjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rpgjuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atacar1;
    private javax.swing.JButton combinado1;
    private javax.swing.JButton curar1;
    private javax.swing.JLabel jugando;
    private javax.swing.JLabel np1;
    private javax.swing.JLabel np2;
    private javax.swing.JProgressBar pb_vida1;
    private javax.swing.JProgressBar pb_vida2;
    private javax.swing.JLabel pj1;
    private javax.swing.JLabel pj2;
    // End of variables declaration//GEN-END:variables

    //int turn;
    
}
